global:
  scrape_interval: 15s

scrape_configs:
  # Scraping Prometheus itself on 192.168.64.20
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.20:9090']

  # Scraping Spring Boot application on 192.168.64.20
  - job_name: 'spring-app'
    metrics_path: 'api/actuator/metrics'
    static_configs:
      - targets: ['192.168.64.20:8089']
